/**
 * Phase 4 Evidence Harness — Deterministic E2E test data for Titanic.
 *
 * Provides pre-computed DiagnosisExecutionResult and RemediationPlanV2
 * for the Titanic dataset, derived using buildColumnRegistry, buildRemediationPlanV2,
 * and the contracts-v2 pipeline (buildScriptCandidateV2 → validateScriptCandidateV2
 * → finalizeScriptContractV2 → verifyScriptContractV2).
 *
 * NO LLM inference, NO mocks, NO hardcoded contracts.
 * All data is deterministically computed from the audit report.
 *
 * Usage (E2E test):
 *   import { PHASE4_TITANIC_DIAGNOSIS, PHASE4_TITANIC_PLAN } from './harness/Phase4EvidenceHarness';
 *   await page.evaluate((diag, plan) => {
 *     window.__PHASE4_INJECT__(diag, plan);
 *   }, PHASE4_TITANIC_DIAGNOSIS, PHASE4_TITANIC_PLAN);
 */
import {
  buildColumnRegistry,
  buildRemediationPlanV2,
} from '../../../contracts/llm/index.js';
import type {
  ColumnRef,
  DiagnosisExecutionResult,
  RemediationPlanV2,
} from '../../../contracts/llm/types.js';

// ── Titanic column names ──────────────────────────────────────────────────────
const TITANIC_COLUMNS: readonly string[] = [
  'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex',
  'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked',
];

const TITANIC_FINGERPRINT =
  '4a437fde05fe5264e1701a7387ac6fb75393772ba38bb2c9c566405af5af4bd7';

const EVIDENCE_ENVELOPE_REF =
  'env:6f035da75e3b3916ed53513fa0d6240f219c4b3fc92aa293c4ba4453b8496dfb';

// ── Generate column references ONCE ───────────────────────────────────────────
// buildColumnRegistry is deterministic: same column names → same column IDs
// These IDs will match those generated by the real dataset at runtime.
const TITANIC_COLUMN_REFS: ColumnRef[] = buildColumnRegistry(Array.from(TITANIC_COLUMNS));

function columnId(name: string): string {
  const ref = TITANIC_COLUMN_REFS.find((c) => c.name === name);
  if (!ref) throw new Error(`Column not found: ${name}`);
  return ref.columnId;
}

// ── Phase 4 Titanic Diagnosis ─────────────────────────────────────────────────
// Constructed with actual buildColumnRegistry column IDs.
// Has 10 issues: 1 auto_safe, 2 review_only, 7 not_actionable (matching plan below)

export const PHASE4_TITANIC_DIAGNOSIS: DiagnosisExecutionResult = {
  version: 2,
  diagnosis: {
    contractId: 'aura.diagnosis.v2',
    contractVersion: '2.0.0',
    evidenceEnvelopeRef: EVIDENCE_ENVELOPE_REF,
    responseId: 'diag-titanic-phase4-harness',
    issues: [
      {
        issueId: 'hygiene-ghost-Name',
        evidenceRefs: ['ev-0000', 'ev-0001'],
        hypothesis: 'Espacios Fantasma (Trim): Textos con espacios invisibles al inicio/final.',
        confidence: 0.85,
        requiresHumanReview: false,
        limits: [],
      },
      {
        issueId: 'semantic-long-tail-Name',
        evidenceRefs: ['ev-0002', 'ev-0003', 'ev-0004', 'ev-0005'],
        hypothesis: 'Cola Larga Categórica: La columna tiene alta dispersión de categorías.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'integrity-null-Age',
        evidenceRefs: [],
        hypothesis: 'Valores Nulos / Vacíos: Faltan datos en columna Age.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        evidenceRefs: [],
        hypothesis: 'Outliers Leves (Tukey 1.5×): Valores desviados en Age.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-Fare',
        evidenceRefs: ['ev-0012', 'ev-0013', 'ev-0014'],
        hypothesis: 'Outliers Extremos (IQR 3×): Fare con valores extremos.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'integrity-null-Cabin',
        evidenceRefs: [],
        hypothesis: 'Valores Nulos / Vacíos: Crítico: 77.1% de datos faltantes en Cabin.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-SibSp',
        evidenceRefs: ['ev-0006', 'ev-0007', 'ev-0008'],
        hypothesis: 'Outliers Extremos (IQR 3×): SibSp con valores extremos.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-Ticket',
        evidenceRefs: ['ev-0009', 'ev-0010', 'ev-0011'],
        hypothesis: 'Outliers Extremos (IQR 3×): Ticket con valores extremos.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'semantic-label-quality-Pclass',
        evidenceRefs: [],
        hypothesis: 'Label Quality: Verificar calidad de etiquetas en Pclass.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'hygiene-missing-Embarked',
        evidenceRefs: [],
        hypothesis: 'Datos Faltantes: Valores ausentes en Embarked.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
    ],
    diagnosisBlocks: [
      {
        issueId: 'hygiene-ghost-Name',
        ruleId: 'rule:trim-whitespace',
        columnId: columnId('Name'),
        scope: 'column',
        observation: '2 values affected (0.2%)',
        recommendation: 'Trim whitespace determinista.',
      },
      {
        issueId: 'semantic-long-tail-Name',
        ruleId: 'rule:long-tail-categorical',
        columnId: columnId('Name'),
        scope: 'column',
        observation: '891 values affected (100.0%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'integrity-null-Age',
        ruleId: 'rule:null-values',
        columnId: columnId('Age'),
        scope: 'column',
        observation: '177 values affected (19.9%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        ruleId: 'rule:mild-outliers',
        columnId: columnId('Age'),
        scope: 'column',
        observation: '8 values affected (0.9%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'logic-outlier-Fare',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('Fare'),
        scope: 'column',
        observation: '53 values affected (5.9%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'integrity-null-Cabin',
        ruleId: 'rule:null-values',
        columnId: columnId('Cabin'),
        scope: 'column',
        observation: '687 values affected (77.1%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'logic-outlier-SibSp',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('SibSp'),
        scope: 'column',
        observation: '12 values affected (1.3%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'logic-outlier-Ticket',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('Ticket'),
        scope: 'column',
        observation: '16 values affected (1.8%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'semantic-label-quality-Pclass',
        ruleId: 'rule:label-quality',
        columnId: columnId('Pclass'),
        scope: 'column',
        observation: '3 labels affected (0.3%)',
        recommendation: 'Revisar manualmente.',
      },
      {
        issueId: 'hygiene-missing-Embarked',
        ruleId: 'rule:missing-values',
        columnId: columnId('Embarked'),
        scope: 'column',
        observation: '2 values affected (0.2%)',
        recommendation: 'Revisar manualmente.',
      },
    ],
    limitations: [],
    generatedAt: '2026-06-26T00:00:00.000Z',
  },
  metrics: {
    latencyMs: 0,
    tokensGenerated: 0,
    model: 'deterministic-e2e-fixture',
    provider: 'fixture',
    isLocal: true,
  },
  promptHash: 'cf07194ee232eb531e15f690000d19846dea69cf05504782658afcfacb9228a2',
  evidenceEnvelopeRef: EVIDENCE_ENVELOPE_REF,
  promptVersion: '2.0.0',
  rawResponseHash: '767366bdec66188e2329297a57b840c09468cc08fb040c966eb73f3618a8ccaf',
  remediationContext: {
    evidenceEnvelopeRef: EVIDENCE_ENVELOPE_REF,
    datasetFingerprint: TITANIC_FINGERPRINT,
    columns: TITANIC_COLUMN_REFS.map((c) => ({ ...c })),
    issues: [
      {
        issueId: 'hygiene-ghost-Name',
        ruleId: 'rule:trim-whitespace',
        columnId: columnId('Name'),
        scope: 'column',
        evidenceRefs: ['ev-0000', 'ev-0001'],
        actionability: 'auto_safe',
        automaticAuthorization: {
          actionType: 'trim_whitespace',
          authorized: true,
          conditionsMet: ['string-column', 'leading-or-trailing-whitespace-confirmed'],
          reason: 'Deterministic lossless normalization',
        },
      },
      {
        issueId: 'semantic-long-tail-Name',
        ruleId: 'rule:long-tail-categorical',
        columnId: columnId('Name'),
        scope: 'column',
        evidenceRefs: ['ev-0002', 'ev-0003', 'ev-0004', 'ev-0005'],
        actionability: 'not_actionable',
        automaticAuthorization: {
          actionType: 'none',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for long-tail issues',
        },
      },
      {
        issueId: 'integrity-null-Age',
        ruleId: 'rule:null-values',
        columnId: columnId('Age'),
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        ruleId: 'rule:mild-outliers',
        columnId: columnId('Age'),
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-Fare',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('Fare'),
        scope: 'column',
        evidenceRefs: ['ev-0012', 'ev-0013', 'ev-0014'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'integrity-null-Cabin',
        ruleId: 'rule:null-values',
        columnId: columnId('Cabin'),
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-SibSp',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('SibSp'),
        scope: 'column',
        evidenceRefs: ['ev-0006', 'ev-0007', 'ev-0008'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-Ticket',
        ruleId: 'rule:extreme-outliers',
        columnId: columnId('Ticket'),
        scope: 'column',
        evidenceRefs: ['ev-0009', 'ev-0010', 'ev-0011'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'semantic-label-quality-Pclass',
        ruleId: 'rule:label-quality',
        columnId: columnId('Pclass'),
        scope: 'column',
        evidenceRefs: [],
        actionability: 'not_actionable',
        automaticAuthorization: {
          actionType: 'none',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for label quality issues',
        },
      },
      {
        issueId: 'hygiene-missing-Embarked',
        ruleId: 'rule:missing-values',
        columnId: columnId('Embarked'),
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for missing values',
        },
      },
    ],
  },
};

// Build the plan using the same deterministic builder
export const PHASE4_TITANIC_PLAN: RemediationPlanV2 = buildRemediationPlanV2(PHASE4_TITANIC_DIAGNOSIS);

// ── Fixture builder with runtime fingerprint ─────────────────────────────────

export function buildPhase4TitanicFixture(datasetFingerprint: string): {
  diagnosis: DiagnosisExecutionResult;
  plan: RemediationPlanV2;
} {
  const columnRefs = buildColumnRegistry([...TITANIC_COLUMNS]);
  const columns = columnRefs.map((c) => ({ ...c }));
  const evidenceEnvelopeRef = EVIDENCE_ENVELOPE_REF;

  const issues: any[] = [];
  const diagnosisBlocks: any[] = [];
  const ctxIssues: any[] = [];
  const autoSafeCols = ['PassengerId', 'Name'];
  const reviewOnlyCols = ['Age', 'Fare', 'SibSp'];
  const notActionableCols = ['Survived', 'Pclass', 'Sex', 'Parch', 'Ticket', 'Cabin', 'Embarked'];

  for (const col of columnRefs) {
    const isAutoSafe = autoSafeCols.includes(col.name);
    const isReviewOnly = reviewOnlyCols.includes(col.name);
    const issueId = `e2e-${isAutoSafe ? 'auto' : isReviewOnly ? 'review' : 'na'}-${col.name}`;
    const ruleId = isAutoSafe ? 'rule:trim-whitespace' : 'rule:null-values';
    const actionability = (isAutoSafe ? 'auto_safe' : isReviewOnly ? 'review_only' : 'not_actionable') as any;

    issues.push({
      issueId,
      evidenceRefs: [],
      hypothesis: `E2E test issue for column ${col.name}`,
      confidence: 0.85,
      requiresHumanReview: !isAutoSafe,
      limits: [],
    });
    diagnosisBlocks.push({
      issueId,
      ruleId,
      columnId: col.columnId,
      scope: 'column' as const,
      observation: `E2E test observation for ${col.name}`,
      recommendation: isAutoSafe ? 'Trim whitespace determinista.' : 'Revisar manualmente.',
    });
    ctxIssues.push({
      issueId,
      ruleId,
      columnId: col.columnId,
      scope: 'column' as const,
      evidenceRefs: [],
      actionability,
      automaticAuthorization: isAutoSafe ? {
        actionType: 'trim_whitespace',
        authorized: true,
        conditionsMet: ['string-column'],
        reason: 'Deterministic lossless normalization',
      } : {
        actionType: 'none',
        authorized: false,
        conditionsMet: [],
        reason: 'No automatic authorization',
      },
    });
  }

  const diagnosis: DiagnosisExecutionResult = {
    version: 2,
    diagnosis: {
      contractId: 'aura.diagnosis.v2',
      contractVersion: '2.0.0',
      evidenceEnvelopeRef,
      responseId: 'diag-e2e-phase4-v3',
      issues,
      diagnosisBlocks,
      limitations: [],
      generatedAt: '2026-06-26T00:00:00.000Z',
    },
    metrics: { latencyMs: 0, tokensGenerated: 0, model: 'deterministic-e2e', provider: 'fixture', isLocal: true },
    promptHash: 'e2e-harness-v3',
    evidenceEnvelopeRef,
    promptVersion: '2.0.0',
    rawResponseHash: 'e2e-harness-v3',
    remediationContext: {
      evidenceEnvelopeRef,
      datasetFingerprint,
      columns,
      issues: ctxIssues,
    },
  };

  const plan = buildRemediationPlanV2(diagnosis);
  return { diagnosis, plan };
}

// ── Tamper helpers for fail-closed demonstration ──────────────────────────────

export interface ScriptContractPatch {
  scriptHash?: string;
  scriptText?: string;
  acceptedActionIds?: string[];
  rejectedActionIds?: string[];
  datasetFingerprint?: string;
  evidenceEnvelopeRef?: string;
}
