/**
 * Phase 3 Evidence Harness — Deterministic E2E test data for Titanic.
 *
 * Provides pre-computed DiagnosisExecutionResult and RemediationPlanV2
 * for Titanic dataset, derived from titanic-audit-report.json using the
 * same contracts-v2 builder functions as production code.
 *
 * NO Ollama, NO LLM inference, NO mocks.
 * All data is deterministically computed from the audit report.
 *
 * Usage (E2E test):
 *   import { PHASE3_TITANIC_DIAGNOSIS, PHASE3_TITANIC_PLAN } from './harness/Phase3EvidenceHarness';
 *   await page.evaluate((diag, plan) => {
 *     window.__PHASE3_INJECT__(diag, plan);
 *   }, PHASE3_TITANIC_DIAGNOSIS, PHASE3_TITANIC_PLAN);
 */
import type { DiagnosisExecutionResult } from '../../../contracts/llm/types.js';
import type { RemediationPlanV2 } from '../../../contracts/llm/types.js';

export const PHASE3_TITANIC_DIAGNOSIS: DiagnosisExecutionResult = {
  version: 2,
  diagnosis: {
    contractId: 'aura.diagnosis.v2',
    contractVersion: '2.0.0',
    evidenceEnvelopeRef: 'env:6f035da75e3b3916ed53513fa0d6240f219c4b3fc92aa293c4ba4453b8496dfb',
    responseId: 'diag-titanic-phase3-harness',
    issues: [
      {
        issueId: 'hygiene-ghost-Name',
        evidenceRefs: ['ev-0000', 'ev-0001'],
        hypothesis: 'Espacios Fantasma (Trim): Textos con espacios invisibles al inicio/final.',
        confidence: 0.85,
        requiresHumanReview: false,
        limits: [],
      },
      {
        issueId: 'semantic-long-tail-Name',
        evidenceRefs: ['ev-0002', 'ev-0003', 'ev-0004', 'ev-0005'],
        hypothesis: 'Cola Larga Categórica: La columna tiene alta dispersión de categorías y baja concentración en los valor',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'integrity-null-Age',
        evidenceRefs: [],
        hypothesis: 'Valores Nulos / Vacíos: Advertencia: Faltan datos.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        evidenceRefs: [],
        hypothesis: 'Outliers Leves (Tukey 1.5×): Valores desviados entre 1.5× y 3× del rango intercuartílico (mild Tukey outliers',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-SibSp',
        evidenceRefs: ['ev-0006', 'ev-0007', 'ev-0008'],
        hypothesis: 'Outliers Extremos (IQR 3×): Valores desviados > 3× del rango intercuartílico.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-tukey-SibSp',
        evidenceRefs: [],
        hypothesis: 'Outliers Leves (Tukey 1.5×): Valores desviados entre 1.5× y 3× del rango intercuartílico (mild Tukey outliers',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-Ticket',
        evidenceRefs: ['ev-0009', 'ev-0010', 'ev-0011'],
        hypothesis: 'Outliers Extremos (IQR 3×): Valores desviados > 3× del rango intercuartílico.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-Fare',
        evidenceRefs: ['ev-0012', 'ev-0013', 'ev-0014'],
        hypothesis: 'Outliers Extremos (IQR 3×): Valores desviados > 3× del rango intercuartílico.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'logic-outlier-tukey-Fare',
        evidenceRefs: [],
        hypothesis: 'Outliers Leves (Tukey 1.5×): Valores desviados entre 1.5× y 3× del rango intercuartílico (mild Tukey outliers',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
      {
        issueId: 'integrity-null-Cabin',
        evidenceRefs: [],
        hypothesis: 'Valores Nulos / Vacíos: Crítico: 77.1% de datos faltantes.',
        confidence: 0.85,
        requiresHumanReview: true,
        limits: [],
      },
    ],
    diagnosisBlocks: [
      {
        issueId: 'hygiene-ghost-Name',
        ruleId: 'rule:trim-whitespace',
        columnId: 'col:72e87fd65ca68696',
        scope: 'column',
        observation: '2 values affected (0.2%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'semantic-long-tail-Name',
        ruleId: 'rule:long-tail-categorical',
        columnId: 'col:72e87fd65ca68696',
        scope: 'column',
        observation: '891 values affected (100.0%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'integrity-null-Age',
        ruleId: 'rule:null-values',
        columnId: 'col:32dea4551abc4b97',
        scope: 'column',
        observation: '177 values affected (19.9%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:32dea4551abc4b97',
        scope: 'column',
        observation: '8 values affected (0.9%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-SibSp',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:97cce996273c77a8',
        scope: 'column',
        observation: '12 values affected (1.3%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-tukey-SibSp',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:97cce996273c77a8',
        scope: 'column',
        observation: '34 values affected (3.8%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-Ticket',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:ddad653362f2b585',
        scope: 'column',
        observation: '16 values affected (1.8%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-Fare',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:6f6266c89cbf773f',
        scope: 'column',
        observation: '53 values affected (5.9%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'logic-outlier-tukey-Fare',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:6f6266c89cbf773f',
        scope: 'column',
        observation: '63 values affected (7.1%)',
        recommendation: 'Revisar y validar manualmente.',
      },
      {
        issueId: 'integrity-null-Cabin',
        ruleId: 'rule:null-values',
        columnId: 'col:08e2224fe0a4ab5f',
        scope: 'column',
        observation: '687 values affected (77.1%)',
        recommendation: 'Revisar y validar manualmente.',
      },
    ],
    limitations: [],
    generatedAt: '2026-06-25T03:27:35.120Z',
  },
  metrics: {
    latencyMs: 150,
    tokensGenerated: 512,
    model: 'qwen2.5:3b',
    provider: 'ollama',
    isLocal: true,
  },
  promptHash: 'cf07194ee232eb531e15f690000d19846dea69cf05504782658afcfacb9228a2',
  evidenceEnvelopeRef: 'env:6f035da75e3b3916ed53513fa0d6240f219c4b3fc92aa293c4ba4453b8496dfb',
  promptVersion: '2.0.0',
  rawResponseHash: '767366bdec66188e2329297a57b840c09468cc08fb040c966eb73f3618a8ccaf',
  remediationContext: {
    evidenceEnvelopeRef: 'env:6f035da75e3b3916ed53513fa0d6240f219c4b3fc92aa293c4ba4453b8496dfb',
    datasetFingerprint: '4a437fde05fe5264e1701a7387ac6fb75393772ba38bb2c9c566405af5af4bd7',
    columns: [
      { columnId: 'col:405641d19bc4d159', name: 'PassengerId', position: 0, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:0d6b69df0e947906', name: 'Survived', position: 1, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:49a73d3af931c597', name: 'Pclass', position: 2, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:72e87fd65ca68696', name: 'Name', position: 3, duplicateOrdinal: 0, isAmbiguous: true, isDuplicate: false },
      { columnId: 'col:17236e209bdcaaf6', name: 'Sex', position: 4, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:32dea4551abc4b97', name: 'Age', position: 5, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:97cce996273c77a8', name: 'SibSp', position: 6, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:ec06bafd72b6c1c0', name: 'Parch', position: 7, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:ddad653362f2b585', name: 'Ticket', position: 8, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:6f6266c89cbf773f', name: 'Fare', position: 9, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:08e2224fe0a4ab5f', name: 'Cabin', position: 10, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
      { columnId: 'col:23da48565e956b52', name: 'Embarked', position: 11, duplicateOrdinal: 0, isAmbiguous: false, isDuplicate: false },
    ],
    issues: [
      {
        issueId: 'hygiene-ghost-Name',
        ruleId: 'rule:trim-whitespace',
        columnId: 'col:72e87fd65ca68696',
        scope: 'column',
        evidenceRefs: ['ev-0000', 'ev-0001'],
        actionability: 'auto_safe',
        automaticAuthorization: {
          actionType: 'trim_whitespace',
          authorized: true,
          conditionsMet: ['string-column', 'leading-or-trailing-whitespace-confirmed'],
          reason: 'Deterministic lossless normalization',
        },
      },
      {
        issueId: 'semantic-long-tail-Name',
        ruleId: 'rule:long-tail-categorical',
        columnId: 'col:72e87fd65ca68696',
        scope: 'column',
        evidenceRefs: ['ev-0002', 'ev-0003', 'ev-0004', 'ev-0005'],
        actionability: 'not_actionable',
        automaticAuthorization: {
          actionType: 'none',
          authorized: false,
          conditionsMet: [],
          reason: 'No automaticAuthorization provided by engine',
        },
      },
      {
        issueId: 'integrity-null-Age',
        ruleId: 'rule:null-values',
        columnId: 'col:32dea4551abc4b97',
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-tukey-Age',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:32dea4551abc4b97',
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-SibSp',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:97cce996273c77a8',
        scope: 'column',
        evidenceRefs: ['ev-0006', 'ev-0007', 'ev-0008'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-tukey-SibSp',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:97cce996273c77a8',
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-Ticket',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:ddad653362f2b585',
        scope: 'column',
        evidenceRefs: ['ev-0009', 'ev-0010', 'ev-0011'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-Fare',
        ruleId: 'rule:extreme-outliers',
        columnId: 'col:6f6266c89cbf773f',
        scope: 'column',
        evidenceRefs: ['ev-0012', 'ev-0013', 'ev-0014'],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'logic-outlier-tukey-Fare',
        ruleId: 'rule:mild-outliers',
        columnId: 'col:6f6266c89cbf773f',
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
      {
        issueId: 'integrity-null-Cabin',
        ruleId: 'rule:null-values',
        columnId: 'col:08e2224fe0a4ab5f',
        scope: 'column',
        evidenceRefs: [],
        actionability: 'review_only',
        automaticAuthorization: {
          actionType: 'null_values',
          authorized: false,
          conditionsMet: [],
          reason: 'No automatic authorization for null/outlier rules',
        },
      },
    ],
  },
};

export const PHASE3_TITANIC_PLAN: RemediationPlanV2 = {
  contractId: 'aura.remediation.v2',
  contractVersion: '2.0.0',
  planId: 'plan:05d7eb1c',
  diagnosisRef: 'diag:caa32d69bf13401191e7516a42e58965dc2d691180827ea92a36d98c3e12e3cd',
  evidenceEnvelopeRef: 'env:6f035da75e3b3916ed53513fa0d6240f219c4b3fc92aa293c4ba4453b8496dfb',
  datasetFingerprint: '4a437fde05fe5264e1701a7387ac6fb75393772ba38bb2c9c566405af5af4bd7',
  plan: [
    {
      actionId: 'act:67de4ee4',
      issueId: 'hygiene-ghost-Name',
      ruleId: 'rule:trim-whitespace',
      columnId: 'col:72e87fd65ca68696',
      actionType: 'trim_whitespace',
      parameters: { trimEdges: true, collapseInternalWhitespace: false },
      actionability: 'review_only',
      evidenceRefs: ['ev-0000', 'ev-0001'],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:a1676846',
      issueId: 'integrity-null-Age',
      ruleId: 'rule:null-values',
      columnId: 'col:32dea4551abc4b97',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: [],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:3252f754',
      issueId: 'logic-outlier-tukey-Age',
      ruleId: 'rule:mild-outliers',
      columnId: 'col:32dea4551abc4b97',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: [],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:2561e20b',
      issueId: 'logic-outlier-SibSp',
      ruleId: 'rule:extreme-outliers',
      columnId: 'col:97cce996273c77a8',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: ['ev-0006', 'ev-0007', 'ev-0008'],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:8c81ab8e',
      issueId: 'logic-outlier-tukey-SibSp',
      ruleId: 'rule:mild-outliers',
      columnId: 'col:97cce996273c77a8',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: [],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:b6dc32c6',
      issueId: 'logic-outlier-Ticket',
      ruleId: 'rule:extreme-outliers',
      columnId: 'col:ddad653362f2b585',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: ['ev-0009', 'ev-0010', 'ev-0011'],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:33a6845c',
      issueId: 'logic-outlier-Fare',
      ruleId: 'rule:extreme-outliers',
      columnId: 'col:6f6266c89cbf773f',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: ['ev-0012', 'ev-0013', 'ev-0014'],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:bd45b163',
      issueId: 'logic-outlier-tukey-Fare',
      ruleId: 'rule:mild-outliers',
      columnId: 'col:6f6266c89cbf773f',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: [],
      approvalStatus: 'pending',
    },
    {
      actionId: 'act:5399ba45',
      issueId: 'integrity-null-Cabin',
      ruleId: 'rule:null-values',
      columnId: 'col:08e2224fe0a4ab5f',
      actionType: 'requires_human_review',
      parameters: { reasonCode: 'review_only_rule' },
      actionability: 'review_only',
      evidenceRefs: [],
      approvalStatus: 'pending',
    },
  ],
  actionabilityMap: {
    'hygiene-ghost-Name': 'review_only',
    'semantic-long-tail-Name': 'not_actionable',
    'integrity-null-Age': 'review_only',
    'logic-outlier-tukey-Age': 'review_only',
    'logic-outlier-SibSp': 'review_only',
    'logic-outlier-tukey-SibSp': 'review_only',
    'logic-outlier-Ticket': 'review_only',
    'logic-outlier-Fare': 'review_only',
    'logic-outlier-tukey-Fare': 'review_only',
    'integrity-null-Cabin': 'review_only',
  },
  exclusions: [
    {
      issueId: 'semantic-long-tail-Name',
      reason: 'not_actionable',
    },
  ],
  generatedAt: '2026-06-25T03:27:35.129Z',
};
