import { test, expect } from '@playwright/test';
import Papa from 'papaparse';
import path from 'node:path';
import fs from 'node:fs';

const root = path.resolve(import.meta.dirname, '../../..');
const examples = path.join(root, 'experiments/rule-engine');
const source = (name: string) => ({ name: `${name}.csv`, mimeType: 'text/csv',
  buffer: Buffer.from(Papa.unparse(JSON.parse(fs.readFileSync(path.join(examples, 'fixtures', `${name}.json`), 'utf8')))) });
const openUpload = async (page: any) => {
  await page.goto('/');
  const start = page.getByRole('button', { name: /Empezar|Comenzar/ }).first();
  if (await start.isVisible()) await start.click();
  await expect(page.getByTestId('csv-file-input')).toBeAttached();
};

test('real upload preserves identifier text and shows every detected problem', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await openUpload(page);
  await page.getByTestId('csv-file-input').setInputFiles(source('clientes_sucio'));
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await page.getByTestId('profile-all-disclosure').locator('summary').first().click();
  const region = page.getByRole('region', { name: 'Todos los hallazgos' });
  await expect(region).toBeVisible();
  await expect(region.getByRole('row')).toHaveCount(15);
  await expect(region.getByText('Posible error de escritura')).toBeVisible();
  await expect(region.getByText('Fecha no válida')).toBeVisible();
  await expect(region.getByRole('rowheader', { name: 'Identificador repetido', exact: true })).toBeVisible();
  await page.getByTestId('profile-tech-disclosure').locator('summary').first().click();
  await page.getByLabel('Columna', { exact: true }).selectOption('documento');
  await expect(page.locator('.col-detail-type-badge')).toContainText('string');
  await page.getByLabel('Columna', { exact: true }).selectOption('email');
  await expect(page.locator('.col-detail-header').filter({ hasText: 'email' })).toContainText('1 hallazgos');
  await expect(page.getByText('OK', { exact: true })).toHaveCount(0);
  fs.mkdirSync(path.join(examples, 'screenshots'), { recursive: true });
  await page.screenshot({ path: path.join(examples, 'screenshots/clientes-general.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByTestId('profile-continue-diagnosis')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(examples, 'screenshots/clientes-mobile.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('CSV alone identifies the suspected spelling and source cells; clean control stays clear', async ({ page }) => {
  await openUpload(page);
  await page.getByTestId('csv-file-input').setInputFiles(path.join(examples, 'fixtures/controlada_sucia.csv'));
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await page.getByTestId('profile-all-disclosure').locator('summary').first().click();
  const findings = page.getByRole('region', { name: 'Todos los hallazgos' });
  await expect(findings.getByRole('row')).toHaveCount(15);
  const typo = findings.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Posible error de escritura' }) });
  await typo.getByText('Ver registros y valores').click();
  await expect(typo).toContainText('Registro 4: "actvo"');
  await expect(typo).toContainText('«actvo» se parece a «activo»');
  const emails = findings.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Formato Email Inválido' }) });
  await emails.getByText('Ver registros y valores').click();
  await expect(emails).toContainText('Registros: 5, 6');
  await expect(emails).toContainText('Registro 5: "no-es-email"');
  await expect(emails).toContainText('Registro 6: "marta@"');
  await typo.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(examples, 'screenshots/controlada-escritura.png') });
  await page.getByRole('button', { name: 'Nuevo análisis', exact: true }).click();
  await page.getByTestId('new-analysis-confirm').click();
  await page.getByRole('button', { name: /Empezar|Comenzar/ }).first().click();
  await page.getByTestId('csv-file-input').setInputFiles(path.join(examples, 'fixtures/controlada_limpia.csv'));
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await expect(page.getByText('No se encontraron avisos prioritarios.')).toBeVisible();
  await expect(page.getByTestId('profile-score-disclosure').locator('summary')).toContainText('100/100');
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' })).toHaveCount(0);
});

test('declared rules find invalid states and the clean exercise has no alerts', async ({ page }) => {
  await openUpload(page);
  await page.getByTestId('csv-file-input').setInputFiles(source('clientes_sucio'));
  await page.getByText('Opciones avanzadas: importar reglas').click();
  await page.getByLabel('Archivo de reglas (.json)').setInputFiles(path.join(examples, 'clientes.rules.json'));
  await expect(page.getByText('Reglas listas: clientes.rules.json')).toBeVisible();
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await page.getByTestId('profile-all-disclosure').locator('summary').first().click();
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' }).getByText('Valor no permitido', { exact: true })).toBeVisible();
  await expect(page.getByText('Número fuera de la regla declarada', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(examples, 'screenshots/clientes-con-reglas.png'), fullPage: true });
  await page.getByRole('button', { name: 'Nuevo análisis', exact: true }).click();
  const confirm = page.getByTestId('new-analysis-dialog');
  await expect(confirm).toBeVisible();
  await confirm.getByTestId('new-analysis-confirm').click();
  await page.getByRole('button', { name: /Empezar|Comenzar/ }).first().click();
  await expect(page.getByTestId('csv-file-input')).toBeAttached();
  await page.getByTestId('csv-file-input').setInputFiles(source('clientes_groundtruth'));
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await expect(page.getByText('No se encontraron avisos prioritarios.')).toBeVisible();
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' })).toHaveCount(0);
});

test('person chooses exceptions graphically before analysis and sees them in the result', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await openUpload(page);
  await page.screenshot({ path: path.join(examples, 'screenshots/carga-editorial.png'), animations: 'disabled' });
  await page.getByTestId('csv-file-input').setInputFiles(path.join(examples, 'fixtures/controlada_sucia.csv'));
  await expect(page.getByRole('heading', { name: 'Reglas y excepciones', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' })).toHaveCount(0);
  const doc = page.locator('.dataset-rule-column').filter({ has: page.locator('summary span').getByText('documento', { exact: true }) });
  await doc.locator('summary').click();
  await doc.getByLabel('Valores repetidos').selectOption('false');
  await doc.getByLabel('Celdas vacías').selectOption('false');
  const amount = page.locator('.dataset-rule-column').filter({ has: page.locator('summary span').getByText('value', { exact: true }) });
  await amount.locator('summary').click();
  await amount.getByLabel('Números negativos').selectOption('true');
  const status = page.locator('.dataset-rule-column').filter({ has: page.locator('summary span').getByText('estado', { exact: true }) });
  await status.locator('summary').click();
  await status.getByLabel('Valores permitidos (uno por línea)').fill('activo\ninactivo\npendiente');
  await page.screenshot({ path: path.join(examples, 'screenshots/reglas-editorial.png'), animations: 'disabled', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(examples, 'screenshots/reglas-editorial-mobile.png'), animations: 'disabled', fullPage: true });
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await page.getByTestId('profile-rules-disclosure').locator('summary').first().click();
  const applied = page.getByRole('region', { name: 'Reglas y excepciones aplicadas' });
  await expect(applied).toContainText('Se permiten repetidos');
  await expect(applied).toContainText('Se permiten negativos');
  await page.getByTestId('profile-all-disclosure').locator('summary').first().click();
  const findings = page.getByRole('region', { name: 'Todos los hallazgos' });
  await expect(findings.getByText('Identificador repetido', { exact: true })).toHaveCount(0);
  await expect(findings.getByText('Negativos Imposibles', { exact: true })).toHaveCount(0);
  await expect(findings.getByText('Valor no permitido', { exact: true })).toBeVisible();
  await expect(findings.getByText('Fecha no válida', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('profile starts with three priorities and opens evidence, all findings and one column on request', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await openUpload(page);
  await page.getByTestId('csv-file-input').setInputFiles(path.join(examples, 'fixtures/controlada_sucia.csv'));
  await page.getByRole('button', { name: 'Analizar dataset', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Revisión inicial', exact: true })).toBeVisible();
  await expect(page.getByTestId('profile-priority-item')).toHaveCount(3);
  await expect(page.getByText('Hay 3 avisos prioritarios para revisar.')).toBeVisible();
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' })).toHaveCount(0);
  await expect(page.getByTestId('profile-column-table')).not.toBeVisible();
  await expect(page.locator('.severity-distribution')).toHaveCount(0);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: path.join(examples, 'screenshots/perfil-resumen.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: path.join(examples, 'screenshots/perfil-resumen-mobile.png'), fullPage: true, animations: 'disabled' });
  const first = page.getByTestId('profile-priority-item').first().locator('summary');
  await first.focus(); await page.keyboard.press('Enter');
  await expect(page.getByTestId('profile-priority-item').first()).toHaveAttribute('open', '');
  await expect(page.getByTestId('profile-priority-item').first().getByText('Registro 5:', { exact: false })).toBeVisible();
  await page.getByTestId('profile-all-disclosure').locator('summary').first().click();
  await expect(page.getByRole('region', { name: 'Todos los hallazgos' }).getByRole('row')).toHaveCount(15);
  await page.getByTestId('profile-tech-disclosure').locator('summary').first().click();
  await page.getByLabel('Columna', { exact: true }).selectOption('documento');
  await expect(page.locator('.col-detail')).toHaveCount(1);
  await expect(page.getByTestId('profile-column-detail')).toContainText('0011223344');
  await page.getByLabel('Columna', { exact: true }).selectOption('value');
  await expect(page.locator('.col-detail')).toHaveCount(1);
  await expect(page.getByTestId('profile-column-detail')).toContainText('value');
  await page.getByTestId('profile-score-disclosure').locator('summary').click();
  await expect(page.getByText('No es un porcentaje de datos correctos ni una medida de precisión.', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
